/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marketproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavishka Sulakshana
 */
public class UpdateStock extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStock
     */
    public UpdateStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itmName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameChk = new javax.swing.JCheckBox();
        priceChk = new javax.swing.JCheckBox();
        qtyChk = new javax.swing.JCheckBox();
        mQtyChk = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        updateVal = new javax.swing.JTextField();
        updtLbl = new javax.swing.JLabel();
        UpdtBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Stock");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ITEM ID");

        itmName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itmName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("What do you want to update");

        buttonGroup1.add(nameChk);
        nameChk.setText("Name");
        nameChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameChkActionPerformed(evt);
            }
        });

        buttonGroup1.add(priceChk);
        priceChk.setText("Price");
        priceChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceChkActionPerformed(evt);
            }
        });

        buttonGroup1.add(qtyChk);
        qtyChk.setText("Quantity");

        buttonGroup1.add(mQtyChk);
        mQtyChk.setText("Max Qty");
        mQtyChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mQtyChkActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Update value");

        updateVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateValActionPerformed(evt);
            }
        });

        updtLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        UpdtBtn.setText("Update");
        UpdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdtBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(29, 29, 29)
                                        .addComponent(itmName, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(nameChk)
                                        .addGap(18, 18, 18)
                                        .addComponent(priceChk)
                                        .addGap(37, 37, 37)
                                        .addComponent(qtyChk)
                                        .addGap(29, 29, 29)
                                        .addComponent(mQtyChk))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(updateVal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UpdtBtn)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameChk)
                    .addComponent(priceChk)
                    .addComponent(qtyChk)
                    .addComponent(mQtyChk))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updateVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(updtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmNameActionPerformed

    private void nameChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameChkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameChkActionPerformed

    private void updateValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateValActionPerformed

    private void priceChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceChkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceChkActionPerformed

    private void mQtyChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mQtyChkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mQtyChkActionPerformed

    private void UpdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdtBtnActionPerformed
        prnt();
    }//GEN-LAST:event_UpdtBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    String query;
    void prnt(){
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dnisupermarket","root",""); 
                    if(nameChk.isSelected()){
                        query = "update product set ProductName = '"+updateVal.getText()+"' where ProductId = '"+
                                itmName.getText()+"';";
                    }
                    else if(priceChk.isSelected()){
                        query = "update product set UnitPrice = '"+updateVal.getText()+"' where ProductId = '"+
                                itmName.getText()+"';";
                    }
                    else if(qtyChk.isSelected()){
                        query = "update product set Quantity = '"+updateVal.getText()+"' where ProductId = '"+
                                itmName.getText()+"';";
                    }
                    else if(mQtyChk.isSelected()){
                        query = "update product set Max_Quantity = '"+updateVal.getText()+"' where ProductId = '"+
                                itmName.getText()+"';";
                    }else{
                        System.out.println("Error");
                        updtLbl.setText("Error");
                    }
                    
                    Statement stmt= con.createStatement();
                    stmt.executeUpdate(query);
                    System.out.println("data saved");
                    con.close();
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f,"Data saved");
                   
}
        catch(ClassNotFoundException | SQLException e){System.out.println(e);}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdtBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField itmName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox mQtyChk;
    private javax.swing.JCheckBox nameChk;
    private javax.swing.JCheckBox priceChk;
    private javax.swing.JCheckBox qtyChk;
    private javax.swing.JTextField updateVal;
    private javax.swing.JLabel updtLbl;
    // End of variables declaration//GEN-END:variables
}
